# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # 파일 경로 표시 라인 에디트
        self.filePathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.filePathLineEdit.setGeometry(QtCore.QRect(20, 50, 350, 30))
        self.filePathLineEdit.setObjectName("filePathLineEdit")
        
        # 파일 탐색 버튼
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(380, 50, 100, 30))
        self.browseButton.setObjectName("browseButton")
        
        # 파일 삭제 버튼
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(180, 100, 120, 40))
        self.deleteButton.setObjectName("deleteButton")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "지우개 소프트웨어"))
        self.browseButton.setText(_translate("MainWindow", "파일 탐색"))
        self.deleteButton.setText(_translate("MainWindow", "파일 삭제"))

